### ISSUE TITLE
Refactor `storage` uploading endpoint

### ISSUE THREAD

**Issue by cmin764** [robocorp/robo#59]
`/upload` -> `/uploads` [here](https://github.com/robocorp/robo/blob/master/storage/src/robocorp/storage/_client.py#L160) in order to align the REST resources to plural.

**Comment by osrjv** [comment]
After this change, we could bump the asset storage library to 1.0, unless there are any objections?

**Comment by osrjv** [comment]
Fixed in commit https://github.com/robocorp/robo/commit/84bb8c802d3ac9314f33c5be14f3a7b369ed6359
